SELECT TOP 2 'HL7_FacilityUDF', * FROM HL7_FacilityUDF
SELECT TOP 2 'HL7_PatientUDF', * FROM HL7_PatientUDF
SELECT TOP 2 'HL7_ProviderUDF', * FROM HL7_ProviderUDF
SELECT TOP 2 'IndicationNote', * FROM IndicationNote
SELECT TOP 2 'InterfaceLog', * FROM InterfaceLog
SELECT TOP 2 'LicenseKey', * FROM LicenseKey
SELECT TOP 2 'Localization', * FROM Localization
SELECT TOP 2 'LockableTable', * FROM LockableTable
SELECT TOP 2 'LoginActivity', * FROM LoginActivity
SELECT TOP 2 'MasterLicense', * FROM MasterLicense
SELECT TOP 2 'NoiseWords', * FROM NoiseWords
SELECT TOP 2 'Outline', * FROM Outline
SELECT TOP 2 'OutlineDocDefInd', * FROM OutlineDocDefInd
SELECT TOP 2 'OutlineDocumentedIndication', * FROM OutlineDocumentedIndication
SELECT TOP 2 'OutlineNote', * FROM OutlineNote
SELECT TOP 2 'PasswordHistory', * FROM PasswordHistory
SELECT TOP 2 'PatchVersion', * FROM PatchVersion
SELECT TOP 2 'Patient', * FROM Patient
SELECT TOP 2 'PatientGroup', * FROM PatientGroup
SELECT TOP 2 'PatientHierarchy', * FROM PatientHierarchy
SELECT TOP 2 'PatientIDSourceGenerator', * FROM PatientIDSourceGenerator
SELECT TOP 2 'PatientSummary', * FROM PatientSummary
SELECT TOP 2 'Progression', * FROM Progression
SELECT TOP 2 'ProgressionElement', * FROM ProgressionElement
SELECT TOP 2 'ProgressionElementNotes', * FROM ProgressionElementNotes
