/**
<summary>
Restore diagram 'diagram_0'
</summary>
<remarks>
Generated by Tool_ScriptDiagram2005/Tool_VarbinaryToVarcharHex
Will attempt to create [sysdiagrams] table if it doesn't already exist
</remarks>
<generated>2011-08-22 11:18</generated>
*/
PRINT '=== Tool_ScriptDiagram2005 restore diagram [diagram_0] ==='
	-- If the sysdiagrams table has not been created in this database, create it!
				IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'sysdiagrams')
				BEGIN
					-- Create table script generated by Sql Server Management Studio
					-- _Assume_ this is roughly equivalent to what Sql Server/Management Studio
					-- creates the first time you add a diagram to a 2005 database
					CREATE TABLE [dbo].[sysdiagrams](
						[name] [sysname] NOT NULL,
						[principal_id] [int] NOT NULL,
						[diagram_id] [int] IDENTITY(1,1) NOT NULL,
						[version] [int] NULL,
						[definition] [varbinary](max) NULL,
					PRIMARY KEY CLUSTERED 
					(
						[diagram_id] ASC
					)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ,
					 CONSTRAINT [UK_principal_name] UNIQUE NONCLUSTERED 
					(
						[principal_id] ASC,
						[name] ASC
					)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) 
					) 
					EXEC sys.sp_addextendedproperty @name=N'microsoft_database_tools_support', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'sysdiagrams'
					PRINT '[sysdiagrams] table was created as it did not already exist'
				END
				-- Target table will now exist, if it didn't before
SET NOCOUNT ON -- Hide (1 row affected) messages
DECLARE @newid INT
DECLARE @DiagramSuffix          varchar (50)
 
PRINT 'Suffix diagram name with date, to ensure uniqueness'
SET @DiagramSuffix = ' ' + LEFT(CONVERT(VARCHAR(23), GETDATE(), 121), 16)
 
PRINT 'Create row for new diagram'
BEGIN TRY
    PRINT 'Write diagram diagram_0 into new row (and get [diagram_id])'
    INSERT INTO sysdiagrams ([name], [principal_id], [version], [definition]) VALUES ('Diagram_0'+@DiagramSuffix, 1, 1, 0x)
    SET @newid = SCOPE_IDENTITY()
END TRY
BEGIN CATCH
    PRINT 'XxXxX ' + Error_Message() + ' XxXxX'
    PRINT 'XxXxX END Tool_ScriptDiagram2005 - fix the error before running again XxXxX'
    RETURN
END CATCH
 
PRINT 'Now add all the binary data...'
BEGIN TRY
    UPDATE sysdiagrams SET [definition] .Write ( 0xD0CF11E0A1B11AE1000000000000000000000000000000003E000300FEFF0900, null, 0) WHERE diagram_id = @newid -- index:1
    UPDATE sysdiagrams SET [definition] .Write ( 0x0600000000000000000000000100000001000000000000000010000002000000, null, 0) WHERE diagram_id = @newid -- index:33
    UPDATE sysdiagrams SET [definition] .Write ( 0x01000000FEFFFFFF0000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:65
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:97
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:129
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:161
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:193
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:225
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:257
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:289
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:321
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:353
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:385
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:417
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:449
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:481
    UPDATE sysdiagrams SET [definition] .Write ( 0xFDFFFFFF13000000FEFFFFFF0400000005000000060000001E00000008000000, null, 0) WHERE diagram_id = @newid -- index:513
    UPDATE sysdiagrams SET [definition] .Write ( 0x090000000A0000000B0000000C0000000D0000000E0000000F00000010000000, null, 0) WHERE diagram_id = @newid -- index:545
    UPDATE sysdiagrams SET [definition] .Write ( 0x1100000012000000FEFFFFFFFEFFFFFF15000000160000001700000018000000, null, 0) WHERE diagram_id = @newid -- index:577
    UPDATE sysdiagrams SET [definition] .Write ( 0x190000001A0000001B0000001C0000001D000000FEFFFFFF1F000000FEFFFFFF, null, 0) WHERE diagram_id = @newid -- index:609
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:641
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:673
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:705
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:737
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:769
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:801
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:833
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:865
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:897
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:929
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:961
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:993
    UPDATE sysdiagrams SET [definition] .Write ( 0x52006F006F007400200045006E00740072007900000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1025
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1057
    UPDATE sysdiagrams SET [definition] .Write ( 0x16000500FFFFFFFFFFFFFFFF0200000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1089
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000000000000000A02C8FACF560CC0103000000C00B000000000000, null, 0) WHERE diagram_id = @newid -- index:1121
    UPDATE sysdiagrams SET [definition] .Write ( 0x6600000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1153
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1185
    UPDATE sysdiagrams SET [definition] .Write ( 0x04000201FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1217
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000E07000000000000, null, 0) WHERE diagram_id = @newid -- index:1249
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F00000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1281
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1313
    UPDATE sysdiagrams SET [definition] .Write ( 0x040002010100000004000000FFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1345
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000000000000000000000000000000007000000E616000000000000, null, 0) WHERE diagram_id = @newid -- index:1377
    UPDATE sysdiagrams SET [definition] .Write ( 0x010043006F006D0070004F0062006A0000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1409
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1441
    UPDATE sysdiagrams SET [definition] .Write ( 0x12000201FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1473
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000000000000000000000000000001D0000005F00000000000000, null, 0) WHERE diagram_id = @newid -- index:1505
    UPDATE sysdiagrams SET [definition] .Write ( 0x0100000002000000030000000400000005000000060000000700000008000000, null, 0) WHERE diagram_id = @newid -- index:1537
    UPDATE sysdiagrams SET [definition] .Write ( 0x090000000A0000000B0000000C0000000D0000000E0000000F00000010000000, null, 0) WHERE diagram_id = @newid -- index:1569
    UPDATE sysdiagrams SET [definition] .Write ( 0x1100000012000000130000001400000015000000160000001700000018000000, null, 0) WHERE diagram_id = @newid -- index:1601
    UPDATE sysdiagrams SET [definition] .Write ( 0x190000001A0000001B0000001C000000FEFFFFFF1E000000FEFFFFFFFEFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1633
    UPDATE sysdiagrams SET [definition] .Write ( 0x2100000022000000230000002400000025000000260000002700000028000000, null, 0) WHERE diagram_id = @newid -- index:1665
    UPDATE sysdiagrams SET [definition] .Write ( 0x290000002A0000002B0000002C0000002D000000FEFFFFFFFEFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1697
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1729
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1761
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1793
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1825
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1857
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1889
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1921
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1953
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1985
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:2017
    UPDATE sysdiagrams SET [definition] .Write ( 0x000428000A0E100C05000080140000000F00FFFF14000000007D00002F8A0000, null, 0) WHERE diagram_id = @newid -- index:2049
    UPDATE sysdiagrams SET [definition] .Write ( 0xB04C00001B9100007E7E0000DE805B10F195D011B0A000AA00BDCB5C00000800, null, 0) WHERE diagram_id = @newid -- index:2081
    UPDATE sysdiagrams SET [definition] .Write ( 0x3000000000020000030000003C006B0000000900000000000000D9E6B0E91C81, null, 0) WHERE diagram_id = @newid -- index:2113
    UPDATE sysdiagrams SET [definition] .Write ( 0xD011AD5100A0C90F5739F43B7F847F61C74385352986E1D552F8A0327DB2D862, null, 0) WHERE diagram_id = @newid -- index:2145
    UPDATE sysdiagrams SET [definition] .Write ( 0x95428D98273C25A2DA2D00002800430000000000000053444DD2011FD1118E63, null, 0) WHERE diagram_id = @newid -- index:2177
    UPDATE sysdiagrams SET [definition] .Write ( 0x006097D2DF4834C9D2777977D811907000065B840D9C00002800430000000000, null, 0) WHERE diagram_id = @newid -- index:2209
    UPDATE sysdiagrams SET [definition] .Write ( 0x000051444DD2011FD1118E63006097D2DF4834C9D2777977D811907000065B84, null, 0) WHERE diagram_id = @newid -- index:2241
    UPDATE sysdiagrams SET [definition] .Write ( 0x0D9C13000000240600000093010E00003C00A50900000700008001000000AA02, null, 0) WHERE diagram_id = @newid -- index:2273
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000800000120000805363684772696400D02000000000000043617365436F, null, 0) WHERE diagram_id = @newid -- index:2305
    UPDATE sysdiagrams SET [definition] .Write ( 0x6E7461637420286943434729000000003C00A50900000700008002000000AA02, null, 0) WHERE diagram_id = @newid -- index:2337
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000800000120000805363684772696400F84300009E070000436F6E746163, null, 0) WHERE diagram_id = @newid -- index:2369
    UPDATE sysdiagrams SET [definition] .Write ( 0x742028506C6174666F726D29000000003400A509000007000080030000009C02, null, 0) WHERE diagram_id = @newid -- index:2401
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000008000000B00008053636847726964003C0F00003A200000436173652028, null, 0) WHERE diagram_id = @newid -- index:2433
    UPDATE sysdiagrams SET [definition] .Write ( 0x69434347290000008000A5090000070000800400000052000000018000005800, null, 0) WHERE diagram_id = @newid -- index:2465
    UPDATE sysdiagrams SET [definition] .Write ( 0x0080436F6E74726F6C00CF1F0000851A000052656C6174696F6E736869702027, null, 0) WHERE diagram_id = @newid -- index:2497
    UPDATE sysdiagrams SET [definition] .Write ( 0x464B5F43617365436F6E746163745F4361736520286943434729272062657477, null, 0) WHERE diagram_id = @newid -- index:2529
    UPDATE sysdiagrams SET [definition] .Write ( 0x65656E202743617365202869434347292720616E64202743617365436F6E7461, null, 0) WHERE diagram_id = @newid -- index:2561
    UPDATE sysdiagrams SET [definition] .Write ( 0x6374202869434347292700002800B50100000700008005000000310000005900, null, 0) WHERE diagram_id = @newid -- index:2593
    UPDATE sysdiagrams SET [definition] .Write ( 0x000002800000436F6E74726F6C0015220000111E000000008C00A50900000700, null, 0) WHERE diagram_id = @newid -- index:2625
    UPDATE sysdiagrams SET [definition] .Write ( 0x008006000000520000000180000062000080436F6E74726F6C00B9340000EB12, null, 0) WHERE diagram_id = @newid -- index:2657
    UPDATE sysdiagrams SET [definition] .Write ( 0x000052656C6174696F6E736869702027464B5F43617365436F6E746163745F43, null, 0) WHERE diagram_id = @newid -- index:2689
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F6E746163742028694343472927206265747765656E2027436F6E7461637420, null, 0) WHERE diagram_id = @newid -- index:2721
    UPDATE sysdiagrams SET [definition] .Write ( 0x28506C6174666F726D292720616E64202743617365436F6E7461637420286943, null, 0) WHERE diagram_id = @newid -- index:2753
    UPDATE sysdiagrams SET [definition] .Write ( 0x43472927000000002800B50100000700008007000000310000005F0000000280, null, 0) WHERE diagram_id = @newid -- index:2785
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000436F6E74726F6C00F23500007B12000000003800A5090000070000800800, null, 0) WHERE diagram_id = @newid -- index:2817
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000B20200000080000010000080536368477269640032640000542400005265, null, 0) WHERE diagram_id = @newid -- index:2849
    UPDATE sysdiagrams SET [definition] .Write ( 0x6650726F76696465725469746C6500009400A509000007000080090000005200, null, 0) WHERE diagram_id = @newid -- index:2881
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000180000069000080436F6E74726F6C00E15700005323000052656C617469, null, 0) WHERE diagram_id = @newid -- index:2913
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F6E736869702027464B5F436F6E746163745F52656650726F76696465725469, null, 0) WHERE diagram_id = @newid -- index:2945
    UPDATE sysdiagrams SET [definition] .Write ( 0x746C652028506C6174666F726D2927206265747765656E202752656650726F76, null, 0) WHERE diagram_id = @newid -- index:2977
    UPDATE sysdiagrams SET [definition] .Write ( 0x696465725469746C652720616E642027436F6E746163742028506C6174666F72, null, 0) WHERE diagram_id = @newid -- index:3009
    UPDATE sysdiagrams SET [definition] .Write ( 0x6D292700000000002800B5010000070000800A00000031000000690000000280, null, 0) WHERE diagram_id = @newid -- index:3041
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000436F6E74726F6C00CA560000E322000000004400A5090000070000800B00, null, 0) WHERE diagram_id = @newid -- index:3073
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000B802000000800000190000805363684772696400186000001A0400005265, null, 0) WHERE diagram_id = @newid -- index:3105
    UPDATE sysdiagrams SET [definition] .Write ( 0x66436F6E74616374547970652028506C6174666F726D2900000000009800A509, null, 0) WHERE diagram_id = @newid -- index:3137
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000070000800D000000520000000180000070000080436F6E74726F6C00E157, null, 0) WHERE diagram_id = @newid -- index:3169
    UPDATE sysdiagrams SET [definition] .Write ( 0x00009D06000052656C6174696F6E736869702027464B5F436F6E746163745F52, null, 0) WHERE diagram_id = @newid -- index:3201
    UPDATE sysdiagrams SET [definition] .Write ( 0x6566436F6E74616374547970652028506C6174666F726D292720626574776565, null, 0) WHERE diagram_id = @newid -- index:3233
    UPDATE sysdiagrams SET [definition] .Write ( 0x6E2027526566436F6E74616374547970652028506C6174666F726D292720616E, null, 0) WHERE diagram_id = @newid -- index:3265
    UPDATE sysdiagrams SET [definition] .Write ( 0x642027436F6E746163742028506C6174666F726D292700002800B50100000700, null, 0) WHERE diagram_id = @newid -- index:3297
    UPDATE sysdiagrams SET [definition] .Write ( 0x00800E000000310000006500000002800000436F6E74726F6C00A05400002D06, null, 0) WHERE diagram_id = @newid -- index:3329
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000003C00A5090000070000800F000000B402000000800000110000805363, null, 0) WHERE diagram_id = @newid -- index:3361
    UPDATE sysdiagrams SET [definition] .Write ( 0x684772696400302A0000E02E000052656653616C75746174696F6E5479706529, null, 0) WHERE diagram_id = @newid -- index:3393
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000009400A5090000070000801000000052000000018000006B000080436F, null, 0) WHERE diagram_id = @newid -- index:3425
    UPDATE sysdiagrams SET [definition] .Write ( 0x6E74726F6C00193E0000DF2D000052656C6174696F6E736869702027464B5F43, null, 0) WHERE diagram_id = @newid -- index:3457
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F6E746163745F52656653616C75746174696F6E547970652028506C6174666F, null, 0) WHERE diagram_id = @newid -- index:3489
    UPDATE sysdiagrams SET [definition] .Write ( 0x726D2927206265747765656E202752656653616C75746174696F6E5479706527, null, 0) WHERE diagram_id = @newid -- index:3521
    UPDATE sysdiagrams SET [definition] .Write ( 0x20616E642027436F6E746163742028506C6174666F726D29276F00002800B501, null, 0) WHERE diagram_id = @newid -- index:3553
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000700008011000000310000006B00000002800000436F6E74726F6C001D39, null, 0) WHERE diagram_id = @newid -- index:3585
    UPDATE sysdiagrams SET [definition] .Write ( 0x00006F2D000000003000A50900000700008012000000A2020000008000000800, null, 0) WHERE diagram_id = @newid -- index:3617
    UPDATE sysdiagrams SET [definition] .Write ( 0x00805363684772696400EE4D00005A3C0000526566537461746500008400A509, null, 0) WHERE diagram_id = @newid -- index:3649
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000700008013000000520000000180000059000080436F6E74726F6C65ED4C, null, 0) WHERE diagram_id = @newid -- index:3681
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000AB35000052656C6174696F6E736869702027464B5F436F6E746163745F52, null, 0) WHERE diagram_id = @newid -- index:3713
    UPDATE sysdiagrams SET [definition] .Write ( 0x656653746174652028506C6174666F726D2927206265747765656E2027526566, null, 0) WHERE diagram_id = @newid -- index:3745
    UPDATE sysdiagrams SET [definition] .Write ( 0x53746174652720616E642027436F6E746163742028506C6174666F726D292700, null, 0) WHERE diagram_id = @newid -- index:3777
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000002800B50100000700008014000000310000005900000002800000436F, null, 0) WHERE diagram_id = @newid -- index:3809
    UPDATE sysdiagrams SET [definition] .Write ( 0x6E74726F6C65334F0000B4390000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3841
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3873
    UPDATE sysdiagrams SET [definition] .Write ( 0x0100FEFF030A0000FFFFFFFF0000000000000000000000000000000017000000, null, 0) WHERE diagram_id = @newid -- index:3905
    UPDATE sysdiagrams SET [definition] .Write ( 0x4D6963726F736F66742044445320466F726D20322E300010000000456D626564, null, 0) WHERE diagram_id = @newid -- index:3937
    UPDATE sysdiagrams SET [definition] .Write ( 0x646564204F626A6563740000000000F439B27100000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3969
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4001
    UPDATE sysdiagrams SET [definition] .Write ( 0x010003000000000000000C0000000B0000004E61BC0000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4033
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4065
    UPDATE sysdiagrams SET [definition] .Write ( 0x214334120800000015150000401D000078563412070000001401000043006100, null, 0) WHERE diagram_id = @newid -- index:4097
    UPDATE sysdiagrams SET [definition] .Write ( 0x7300650043006F006E0074006100630074002000280069004300430047002900, null, 0) WHERE diagram_id = @newid -- index:4129
    UPDATE sysdiagrams SET [definition] .Write ( 0x00006E003D0032002E0030002E0030002E0030002C002000430075006C007400, null, 0) WHERE diagram_id = @newid -- index:4161
    UPDATE sysdiagrams SET [definition] .Write ( 0x7500720065003D006E00650075007400720061006C002C002000500075006200, null, 0) WHERE diagram_id = @newid -- index:4193
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C00690063004B006500790054006F006B0065006E003D006200370037006100, null, 0) WHERE diagram_id = @newid -- index:4225
    UPDATE sysdiagrams SET [definition] .Write ( 0x3500630035003600310039003300340065003000380039000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4257
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4289
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4321
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000010000000500000054000000, null, 0) WHERE diagram_id = @newid -- index:4353
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C0000002C0000002C00000034000000000000000000000096240000DE200000, null, 0) WHERE diagram_id = @newid -- index:4385
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000002D0100000D0000000C000000070000001C010000BC07000054060000, null, 0) WHERE diagram_id = @newid -- index:4417
    UPDATE sysdiagrams SET [definition] .Write ( 0xD0020000840300007602000038040000460500002A03000046050000AE060000, null, 0) WHERE diagram_id = @newid -- index:4449
    UPDATE sysdiagrams SET [definition] .Write ( 0x92040000000000000100000015150000401D0000000000000B0000000B000000, null, 0) WHERE diagram_id = @newid -- index:4481
    UPDATE sysdiagrams SET [definition] .Write ( 0x02000000020000001C010000AB0900000000000001000000C7110000FF050000, null, 0) WHERE diagram_id = @newid -- index:4513
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000010000000100000002000000020000001C010000BC07000001000000, null, 0) WHERE diagram_id = @newid -- index:4545
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000C7110000ED0300000000000000000000000000000200000002000000, null, 0) WHERE diagram_id = @newid -- index:4577
    UPDATE sysdiagrams SET [definition] .Write ( 0x1C010000BC0700000000000000000000072C0000DE2000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4609
    UPDATE sysdiagrams SET [definition] .Write ( 0x0D00000004000000040000001C010000BC07000024090000A005000078563412, null, 0) WHERE diagram_id = @newid -- index:4641
    UPDATE sysdiagrams SET [definition] .Write ( 0x040000006200000001000000010000000B000000000000000100000002000000, null, 0) WHERE diagram_id = @newid -- index:4673
    UPDATE sysdiagrams SET [definition] .Write ( 0x030000000400000005000000060000000700000008000000090000000A000000, null, 0) WHERE diagram_id = @newid -- index:4705
    UPDATE sysdiagrams SET [definition] .Write ( 0x05000000690043004300470000000C000000430061007300650043006F006E00, null, 0) WHERE diagram_id = @newid -- index:4737
    UPDATE sysdiagrams SET [definition] .Write ( 0x74006100630074000000214334120800000015150000C8300000785634120700, null, 0) WHERE diagram_id = @newid -- index:4769
    UPDATE sysdiagrams SET [definition] .Write ( 0x00001401000043006F006E0074006100630074002000280050006C0061007400, null, 0) WHERE diagram_id = @newid -- index:4801
    UPDATE sysdiagrams SET [definition] .Write ( 0x66006F0072006D00290000000000010000000048A0721000E8050C0000001F00, null, 0) WHERE diagram_id = @newid -- index:4833
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000020000000300000005000000F4FFFFFF1000E805170000001F0000000300, null, 0) WHERE diagram_id = @newid -- index:4865
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000001000000F4FFFFFF1000E8052B0000005C000000020000000300, null, 0) WHERE diagram_id = @newid -- index:4897
    UPDATE sysdiagrams SET [definition] .Write ( 0x000005000000F4FFFFFF1000E8055C0000007D00000002000000030000000500, null, 0) WHERE diagram_id = @newid -- index:4929
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000F4FFFFFF1000E8050C0000007D000000010000000000000007000000F4FF, null, 0) WHERE diagram_id = @newid -- index:4961
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFF1000E8057D00000086000000020000000300000005000000F4FFFFFF1000, null, 0) WHERE diagram_id = @newid -- index:4993
    UPDATE sysdiagrams SET [definition] .Write ( 0xE8052B0000009000000004000000080000000500000000000000000000000100, null, 0) WHERE diagram_id = @newid -- index:5025
    UPDATE sysdiagrams SET [definition] .Write ( 0x000005000000540000002C0000002C0000002C00000034000000000000000000, null, 0) WHERE diagram_id = @newid -- index:5057
    UPDATE sysdiagrams SET [definition] .Write ( 0x000096240000DE200000000000002D0100000D0000000C000000070000001C01, null, 0) WHERE diagram_id = @newid -- index:5089
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000BC07000054060000D0020000840300007602000038040000460500002A03, null, 0) WHERE diagram_id = @newid -- index:5121
    UPDATE sysdiagrams SET [definition] .Write ( 0x000046050000AE06000092040000000000000100000015150000C83000000000, null, 0) WHERE diagram_id = @newid -- index:5153
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000140000000C00000002000000020000001C010000AB090000000000000100, null, 0) WHERE diagram_id = @newid -- index:5185
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000C7110000FF05000000000000010000000100000002000000020000001C01, null, 0) WHERE diagram_id = @newid -- index:5217
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000BC0700000100000000000000C7110000ED03000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:5249
    UPDATE sysdiagrams SET [definition] .Write ( 0x000002000000020000001C010000BC0700000000000000000000072C0000DE20, null, 0) WHERE diagram_id = @newid -- index:5281
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000000000000D00000004000000040000001C010000BC0700002409, null, 0) WHERE diagram_id = @newid -- index:5313
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000A005000078563412040000006200000001000000010000000B0000000000, null, 0) WHERE diagram_id = @newid -- index:5345
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000010000000200000003000000040000000500000006000000070000000800, null, 0) WHERE diagram_id = @newid -- index:5377
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000090000000A0000000900000050006C006100740066006F0072006D000000, null, 0) WHERE diagram_id = @newid -- index:5409
    UPDATE sysdiagrams SET [definition] .Write ( 0x0800000043006F006E0074006100630074000000214334120800000015150000, null, 0) WHERE diagram_id = @newid -- index:5441
    UPDATE sysdiagrams SET [definition] .Write ( 0xC830000078563412070000001401000043006100730065002000280069004300, null, 0) WHERE diagram_id = @newid -- index:5473
    UPDATE sysdiagrams SET [definition] .Write ( 0x43004700290000007300750061006C00530074007500640069006F002E007600, null, 0) WHERE diagram_id = @newid -- index:5505
    UPDATE sysdiagrams SET [definition] .Write ( 0x73007000530071006C0045006E0075006D002C00200056006500720073006900, null, 0) WHERE diagram_id = @newid -- index:5537
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F006E003D0039002E0030002E003200340032002E0030002C00200043007500, null, 0) WHERE diagram_id = @newid -- index:5569
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C0074007500720065003D006E00650075007400720061006C002C0020005000, null, 0) WHERE diagram_id = @newid -- index:5601
    UPDATE sysdiagrams SET [definition] .Write ( 0x750062006C00690063004B006500790054006F006B0065006E003D0038003900, null, 0) WHERE diagram_id = @newid -- index:5633
    UPDATE sysdiagrams SET [definition] .Write ( 0x3800340035006400630064003800300038003000630063003900310000000000, null, 0) WHERE diagram_id = @newid -- index:5665
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:5697
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000000100000005000000540000002C0000002C0000002C000000, null, 0) WHERE diagram_id = @newid -- index:5729
    UPDATE sysdiagrams SET [definition] .Write ( 0x34000000000000000000000096240000DE200000000000002D0100000D000000, null, 0) WHERE diagram_id = @newid -- index:5761
    UPDATE sysdiagrams SET [definition] .Write ( 0x0C000000070000001C010000BC07000054060000D00200008403000076020000, null, 0) WHERE diagram_id = @newid -- index:5793
    UPDATE sysdiagrams SET [definition] .Write ( 0x38040000460500002A03000046050000AE060000920400000000000001000000, null, 0) WHERE diagram_id = @newid -- index:5825
    UPDATE sysdiagrams SET [definition] .Write ( 0x15150000C830000000000000140000000C00000002000000020000001C010000, null, 0) WHERE diagram_id = @newid -- index:5857
    UPDATE sysdiagrams SET [definition] .Write ( 0xAB0900000000000001000000C7110000320C0000000000000400000004000000, null, 0) WHERE diagram_id = @newid -- index:5889
    UPDATE sysdiagrams SET [definition] .Write ( 0x02000000020000001C010000BC0700000100000000000000C7110000ED030000, null, 0) WHERE diagram_id = @newid -- index:5921
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000000000000002000000020000001C010000BC07000000000000, null, 0) WHERE diagram_id = @newid -- index:5953
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000072C0000DE20000000000000000000000D0000000400000004000000, null, 0) WHERE diagram_id = @newid -- index:5985
    UPDATE sysdiagrams SET [definition] .Write ( 0x1C010000BC07000024090000A005000078563412040000005400000001000000, null, 0) WHERE diagram_id = @newid -- index:6017
    UPDATE sysdiagrams SET [definition] .Write ( 0x010000000B000000000000000100000002000000030000000400000005000000, null, 0) WHERE diagram_id = @newid -- index:6049
    UPDATE sysdiagrams SET [definition] .Write ( 0x060000000700000008000000090000000A000000050000006900430043004700, null, 0) WHERE diagram_id = @newid -- index:6081
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000050000004300610073006500000002000B00662100003A20000066210000, null, 0) WHERE diagram_id = @newid -- index:6113
    UPDATE sysdiagrams SET [definition] .Write ( 0x401D00000000000002000000F0F0F00000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6145
    UPDATE sysdiagrams SET [definition] .Write ( 0x01000000050000000000000015220000111E0000630C00005801000032000000, null, 0) WHERE diagram_id = @newid -- index:6177
    UPDATE sysdiagrams SET [definition] .Write ( 0x010000020000630C000058010000020000000000050000800800008001000000, null, 0) WHERE diagram_id = @newid -- index:6209
    UPDATE sysdiagrams SET [definition] .Write ( 0x150001000000900144420100065461686F6D61130046004B005F004300610073, null, 0) WHERE diagram_id = @newid -- index:6241
    UPDATE sysdiagrams SET [definition] .Write ( 0x00650043006F006E0074006100630074005F00430061007300650002000B00F8, null, 0) WHERE diagram_id = @newid -- index:6273
    UPDATE sysdiagrams SET [definition] .Write ( 0x43000082140000E5350000821400000000000002000000F0F0F0000000000000, null, 0) WHERE diagram_id = @newid -- index:6305
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000010000000700000000000000F23500007B120000F8, null, 0) WHERE diagram_id = @newid -- index:6337
    UPDATE sysdiagrams SET [definition] .Write ( 0x0D00005801000032000000010000020000F80D00005801000002000000000005, null, 0) WHERE diagram_id = @newid -- index:6369
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000800800008001000000150001000000900144420100065461686F6D611600, null, 0) WHERE diagram_id = @newid -- index:6401
    UPDATE sysdiagrams SET [definition] .Write ( 0x46004B005F00430061007300650043006F006E0074006100630074005F004300, null, 0) WHERE diagram_id = @newid -- index:6433
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F006E007400610063007400214334120800000015150000141B000078563412, null, 0) WHERE diagram_id = @newid -- index:6465
    UPDATE sysdiagrams SET [definition] .Write ( 0x0700000014010000520065006600500072006F00760069006400650072005400, null, 0) WHERE diagram_id = @newid -- index:6497
    UPDATE sysdiagrams SET [definition] .Write ( 0x690074006C006500000074007500640069006F002E0076007300700053007100, null, 0) WHERE diagram_id = @newid -- index:6529
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C0045006E0075006D002C002000560065007200730069006F006E003D003900, null, 0) WHERE diagram_id = @newid -- index:6561
    UPDATE sysdiagrams SET [definition] .Write ( 0x2E0030002E003200340032002E0030002C002000430075006C00740075007200, null, 0) WHERE diagram_id = @newid -- index:6593
    UPDATE sysdiagrams SET [definition] .Write ( 0x65003D006E00650075007400720061006C002C0020005000750062006C006900, null, 0) WHERE diagram_id = @newid -- index:6625
    UPDATE sysdiagrams SET [definition] .Write ( 0x63004B006500790054006F006B0065006E003D00380039003800340035006400, null, 0) WHERE diagram_id = @newid -- index:6657
    UPDATE sysdiagrams SET [definition] .Write ( 0x6300640038003000380030006300630039003100000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6689
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6721
    UPDATE sysdiagrams SET [definition] .Write ( 0x0100000005000000540000002C0000002C0000002C0000003400000000000000, null, 0) WHERE diagram_id = @newid -- index:6753
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000096240000CD1E0000000000002D0100000C0000000C00000007000000, null, 0) WHERE diagram_id = @newid -- index:6785
    UPDATE sysdiagrams SET [definition] .Write ( 0x1C010000BC07000054060000D002000084030000760200003804000046050000, null, 0) WHERE diagram_id = @newid -- index:6817
    UPDATE sysdiagrams SET [definition] .Write ( 0x2A03000046050000AE06000092040000000000000100000015150000141B0000, null, 0) WHERE diagram_id = @newid -- index:6849
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000A0000000A00000002000000020000001C010000AB09000000000000, null, 0) WHERE diagram_id = @newid -- index:6881
    UPDATE sysdiagrams SET [definition] .Write ( 0x01000000C7110000FF0500000000000001000000010000000200000002000000, null, 0) WHERE diagram_id = @newid -- index:6913
    UPDATE sysdiagrams SET [definition] .Write ( 0x1C010000BC0700000100000000000000C7110000ED0300000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6945
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000002000000020000001C010000BC0700000000000000000000072C0000, null, 0) WHERE diagram_id = @newid -- index:6977
    UPDATE sysdiagrams SET [definition] .Write ( 0xDE20000000000000000000000D00000004000000040000001C010000BC070000, null, 0) WHERE diagram_id = @newid -- index:7009
    UPDATE sysdiagrams SET [definition] .Write ( 0x24090000A005000078563412040000006A00000001000000010000000B000000, null, 0) WHERE diagram_id = @newid -- index:7041
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000001000000020000000300000004000000050000000600000007000000, null, 0) WHERE diagram_id = @newid -- index:7073
    UPDATE sysdiagrams SET [definition] .Write ( 0x08000000090000000A00000004000000640062006F0000001100000052006500, null, 0) WHERE diagram_id = @newid -- index:7105
    UPDATE sysdiagrams SET [definition] .Write ( 0x6600500072006F00760069006400650072005400690074006C00650000000200, null, 0) WHERE diagram_id = @newid -- index:7137
    UPDATE sysdiagrams SET [definition] .Write ( 0x0B0032640000EA2400000D590000EA2400000000000002000000F0F0F0000000, null, 0) WHERE diagram_id = @newid -- index:7169
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000010000000A00000000000000CA560000E322, null, 0) WHERE diagram_id = @newid -- index:7201
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000A90F00005801000032000000010000020000A90F00005801000002000000, null, 0) WHERE diagram_id = @newid -- index:7233
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000050000800800008001000000150001000000900144420100065461686F6D, null, 0) WHERE diagram_id = @newid -- index:7265
    UPDATE sysdiagrams SET [definition] .Write ( 0x611B0046004B005F0043006F006E0074006100630074005F0052006500660050, null, 0) WHERE diagram_id = @newid -- index:7297
    UPDATE sysdiagrams SET [definition] .Write ( 0x0072006F00760069006400650072005400690074006C00650021433412080000, null, 0) WHERE diagram_id = @newid -- index:7329
    UPDATE sysdiagrams SET [definition] .Write ( 0x0064180000E818000078563412070000001401000052006500660043006F006E, null, 0) WHERE diagram_id = @newid -- index:7361
    UPDATE sysdiagrams SET [definition] .Write ( 0x00740061006300740054007900700065002000280050006C006100740066006F, null, 0) WHERE diagram_id = @newid -- index:7393
    UPDATE sysdiagrams SET [definition] .Write ( 0x0072006D00290000002E0030002C002000430075006C0074007500720065003D, null, 0) WHERE diagram_id = @newid -- index:7425
    UPDATE sysdiagrams SET [definition] .Write ( 0x006E00650075007400720061006C002C0020005000750062006C00690063004B, null, 0) WHERE diagram_id = @newid -- index:7457
    UPDATE sysdiagrams SET [definition] .Write ( 0x006500790054006F006B0065006E003D00620037003700610035006300350036, null, 0) WHERE diagram_id = @newid -- index:7489
    UPDATE sysdiagrams SET [definition] .Write ( 0x0031003900330034006500300038003900000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:7521
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:7553
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:7585
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000000000000000000100000005000000540000002C0000002C0000, null, 0) WHERE diagram_id = @newid -- index:7617
    UPDATE sysdiagrams SET [definition] .Write ( 0x002C00000034000000000000000000000096240000BB1C0000000000002D0100, null, 0) WHERE diagram_id = @newid -- index:7649
    UPDATE sysdiagrams SET [definition] .Write ( 0x000B0000000C000000070000001C010000BC07000054060000D0020000840300, null, 0) WHERE diagram_id = @newid -- index:7681
    UPDATE sysdiagrams SET [definition] .Write ( 0x007602000038040000460500002A03000046050000AE06000092040000000000, null, 0) WHERE diagram_id = @newid -- index:7713
    UPDATE sysdiagrams SET [definition] .Write ( 0x000100000064180000E818000000000000090000000900000002000000020000, null, 0) WHERE diagram_id = @newid -- index:7745
    UPDATE sysdiagrams SET [definition] .Write ( 0x001C0100008B0B00000000000001000000C7110000FF05000000000000010000, null, 0) WHERE diagram_id = @newid -- index:7777
    UPDATE sysdiagrams SET [definition] .Write ( 0x000100000002000000020000001C010000BC0700000100000000000000C71100, null, 0) WHERE diagram_id = @newid -- index:7809
    UPDATE sysdiagrams SET [definition] .Write ( 0x00ED03000000000000000000000000000002000000020000001C010000BC0700, null, 0) WHERE diagram_id = @newid -- index:7841
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000000000072C0000DE20000000000000000000000D000000040000, null, 0) WHERE diagram_id = @newid -- index:7873
    UPDATE sysdiagrams SET [definition] .Write ( 0x00040000001C010000BC07000024090000A00500007856341204000000700000, null, 0) WHERE diagram_id = @newid -- index:7905
    UPDATE sysdiagrams SET [definition] .Write ( 0x0001000000010000000B00000000000000010000000200000003000000040000, null, 0) WHERE diagram_id = @newid -- index:7937
    UPDATE sysdiagrams SET [definition] .Write ( 0x0005000000060000000700000008000000090000000A0000000900000050006C, null, 0) WHERE diagram_id = @newid -- index:7969
    UPDATE sysdiagrams SET [definition] .Write ( 0x006100740066006F0072006D0000000F00000052006500660043006F006E0074, null, 0) WHERE diagram_id = @newid -- index:8001
    UPDATE sysdiagrams SET [definition] .Write ( 0x006100630074005400790070006500000002000B0018600000340800000D5900, null, 0) WHERE diagram_id = @newid -- index:8033
    UPDATE sysdiagrams SET [definition] .Write ( 0x00340800000000000002000000F0F0F000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8065
    UPDATE sysdiagrams SET [definition] .Write ( 0x00010000000E00000000000000A05400002D060000E20F000058010000320000, null, 0) WHERE diagram_id = @newid -- index:8097
    UPDATE sysdiagrams SET [definition] .Write ( 0x00010000020000E20F000058010000020000000000FFFFFF0008000080010000, null, 0) WHERE diagram_id = @newid -- index:8129
    UPDATE sysdiagrams SET [definition] .Write ( 0x00150001000000900144420100065461686F6D61190046004B005F0043006F00, null, 0) WHERE diagram_id = @newid -- index:8161
    UPDATE sysdiagrams SET [definition] .Write ( 0x6E0074006100630074005F0052006500660043006F006E007400610063007400, null, 0) WHERE diagram_id = @newid -- index:8193
    UPDATE sysdiagrams SET [definition] .Write ( 0x5400790070006500214334120800000015150000141B00007856341207000000, null, 0) WHERE diagram_id = @newid -- index:8225
    UPDATE sysdiagrams SET [definition] .Write ( 0x14010000520065006600530061006C00750074006100740069006F006E005400, null, 0) WHERE diagram_id = @newid -- index:8257
    UPDATE sysdiagrams SET [definition] .Write ( 0x79007000650000007500640069006F002E00760073007000530071006C004500, null, 0) WHERE diagram_id = @newid -- index:8289
    UPDATE sysdiagrams SET [definition] .Write ( 0x6E0075006D002C002000560065007200730069006F006E003D0039002E003000, null, 0) WHERE diagram_id = @newid -- index:8321
    UPDATE sysdiagrams SET [definition] .Write ( 0x2E003200340032002E0030002C002000430075006C0074007500720065003D00, null, 0) WHERE diagram_id = @newid -- index:8353
    UPDATE sysdiagrams SET [definition] .Write ( 0x6E00650075007400720061006C002C0020005000750062006C00690063004B00, null, 0) WHERE diagram_id = @newid -- index:8385
    UPDATE sysdiagrams SET [definition] .Write ( 0x6500790054006F006B0065006E003D0038003900380034003500640063006400, null, 0) WHERE diagram_id = @newid -- index:8417
    UPDATE sysdiagrams SET [definition] .Write ( 0x3800300038003000630063003900310000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8449
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000001000000, null, 0) WHERE diagram_id = @newid -- index:8481
    UPDATE sysdiagrams SET [definition] .Write ( 0x05000000540000002C0000002C0000002C000000340000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8513
    UPDATE sysdiagrams SET [definition] .Write ( 0x96240000CD1E0000000000002D0100000C0000000C000000070000001C010000, null, 0) WHERE diagram_id = @newid -- index:8545
    UPDATE sysdiagrams SET [definition] .Write ( 0xBC07000054060000D0020000840300007602000038040000460500002A030000, null, 0) WHERE diagram_id = @newid -- index:8577
    UPDATE sysdiagrams SET [definition] .Write ( 0x46050000AE06000092040000000000000100000015150000141B000000000000, null, 0) WHERE diagram_id = @newid -- index:8609
    UPDATE sysdiagrams SET [definition] .Write ( 0x0A0000000A00000002000000020000001C010000AB0900000000000001000000, null, 0) WHERE diagram_id = @newid -- index:8641
    UPDATE sysdiagrams SET [definition] .Write ( 0xC7110000FF05000000000000010000000100000002000000020000001C010000, null, 0) WHERE diagram_id = @newid -- index:8673
    UPDATE sysdiagrams SET [definition] .Write ( 0xBC0700000100000000000000C7110000ED030000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8705
    UPDATE sysdiagrams SET [definition] .Write ( 0x02000000020000001C010000BC0700000000000000000000072C0000DE200000, null, 0) WHERE diagram_id = @newid -- index:8737
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000000D00000004000000040000001C010000BC07000024090000, null, 0) WHERE diagram_id = @newid -- index:8769
    UPDATE sysdiagrams SET [definition] .Write ( 0xA005000078563412040000006C00000001000000010000000B00000000000000, null, 0) WHERE diagram_id = @newid -- index:8801
    UPDATE sysdiagrams SET [definition] .Write ( 0x0100000002000000030000000400000005000000060000000700000008000000, null, 0) WHERE diagram_id = @newid -- index:8833
    UPDATE sysdiagrams SET [definition] .Write ( 0x090000000A00000004000000640062006F000000120000005200650066005300, null, 0) WHERE diagram_id = @newid -- index:8865
    UPDATE sysdiagrams SET [definition] .Write ( 0x61006C00750074006100740069006F006E005400790070006500000002000B00, null, 0) WHERE diagram_id = @newid -- index:8897
    UPDATE sysdiagrams SET [definition] .Write ( 0x453F0000762F0000F8430000762F00000000000002000000F0F0F00000000000, null, 0) WHERE diagram_id = @newid -- index:8929
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000100000011000000000000001D3900006F2D0000, null, 0) WHERE diagram_id = @newid -- index:8961
    UPDATE sysdiagrams SET [definition] .Write ( 0x0211000058010000320000000100000200000211000058010000020000000000, null, 0) WHERE diagram_id = @newid -- index:8993
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFFFF000800008001000000150001000000900144420100065461686F6D611C, null, 0) WHERE diagram_id = @newid -- index:9025
    UPDATE sysdiagrams SET [definition] .Write ( 0x0046004B005F0043006F006E0074006100630074005F00520065006600530061, null, 0) WHERE diagram_id = @newid -- index:9057
    UPDATE sysdiagrams SET [definition] .Write ( 0x006C00750074006100740069006F006E00540079007000650021433412080000, null, 0) WHERE diagram_id = @newid -- index:9089
    UPDATE sysdiagrams SET [definition] .Write ( 0x0015150000141B00007856341207000000140100005200650066005300740061, null, 0) WHERE diagram_id = @newid -- index:9121
    UPDATE sysdiagrams SET [definition] .Write ( 0x007400650000006E0064006F00770073002E0046006F0072006D0073002C0020, null, 0) WHERE diagram_id = @newid -- index:9153
    UPDATE sysdiagrams SET [definition] .Write ( 0x00560065007200730069006F006E003D0032002E0030002E0030002E0030002C, null, 0) WHERE diagram_id = @newid -- index:9185
    UPDATE sysdiagrams SET [definition] .Write ( 0x002000430075006C0074007500720065003D006E00650075007400720061006C, null, 0) WHERE diagram_id = @newid -- index:9217
    UPDATE sysdiagrams SET [definition] .Write ( 0x002C0020005000750062006C00690063004B006500790054006F006B0065006E, null, 0) WHERE diagram_id = @newid -- index:9249
    UPDATE sysdiagrams SET [definition] .Write ( 0x003D006200370037006100350063003500360031003900330034006500300038, null, 0) WHERE diagram_id = @newid -- index:9281
    UPDATE sysdiagrams SET [definition] .Write ( 0x0039000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9313
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9345
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000000000000000000100000005000000540000002C0000002C0000, null, 0) WHERE diagram_id = @newid -- index:9377
    UPDATE sysdiagrams SET [definition] .Write ( 0x002C00000034000000000000000000000096240000CD1E0000000000002D0100, null, 0) WHERE diagram_id = @newid -- index:9409
    UPDATE sysdiagrams SET [definition] .Write ( 0x000C0000000C000000070000001C010000BC07000054060000D0020000840300, null, 0) WHERE diagram_id = @newid -- index:9441
    UPDATE sysdiagrams SET [definition] .Write ( 0x007602000038040000460500002A03000046050000AE06000092040000000000, null, 0) WHERE diagram_id = @newid -- index:9473
    UPDATE sysdiagrams SET [definition] .Write ( 0x000100000015150000141B0000000000000A0000000A00000002000000020000, null, 0) WHERE diagram_id = @newid -- index:9505
    UPDATE sysdiagrams SET [definition] .Write ( 0x001C010000AB0900000000000001000000C7110000FF05000000000000010000, null, 0) WHERE diagram_id = @newid -- index:9537
    UPDATE sysdiagrams SET [definition] .Write ( 0x000100000002000000020000001C010000BC0700000100000000000000C71100, null, 0) WHERE diagram_id = @newid -- index:9569
    UPDATE sysdiagrams SET [definition] .Write ( 0x00ED03000000000000000000000000000002000000020000001C010000BC0700, null, 0) WHERE diagram_id = @newid -- index:9601
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000000000072C0000DE20000000000000000000000D000000040000, null, 0) WHERE diagram_id = @newid -- index:9633
    UPDATE sysdiagrams SET [definition] .Write ( 0x00040000001C010000BC07000024090000A005000078563412040000005A0000, null, 0) WHERE diagram_id = @newid -- index:9665
    UPDATE sysdiagrams SET [definition] .Write ( 0x0001000000010000000B00000000000000010000000200000003000000040000, null, 0) WHERE diagram_id = @newid -- index:9697
    UPDATE sysdiagrams SET [definition] .Write ( 0x0005000000060000000700000008000000090000000A00000004000000640062, null, 0) WHERE diagram_id = @newid -- index:9729
    UPDATE sysdiagrams SET [definition] .Write ( 0x006F0000000900000052006500660053007400610074006500000002000B0084, null, 0) WHERE diagram_id = @newid -- index:9761
    UPDATE sysdiagrams SET [definition] .Write ( 0x4E00005A3C0000844E0000663800000000000002000000F0F0F0000000000000, null, 0) WHERE diagram_id = @newid -- index:9793
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000010000001400000000000000334F0000B4390000D4, null, 0) WHERE diagram_id = @newid -- index:9825
    UPDATE sysdiagrams SET [definition] .Write ( 0x0B00005801000032000000010000020000D40B000058010000020000000000FF, null, 0) WHERE diagram_id = @newid -- index:9857
    UPDATE sysdiagrams SET [definition] .Write ( 0xFFFF000800008001000000150001000000900144420100065461686F6D611300, null, 0) WHERE diagram_id = @newid -- index:9889
    UPDATE sysdiagrams SET [definition] .Write ( 0x46004B005F0043006F006E0074006100630074005F0052006500660053007400, null, 0) WHERE diagram_id = @newid -- index:9921
    UPDATE sysdiagrams SET [definition] .Write ( 0x6100740065000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9953
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9985
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10017
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10049
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10081
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10113
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10145
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10177
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10209
    UPDATE sysdiagrams SET [definition] .Write ( 0x0300440064007300530074007200650061006D00000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10241
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10273
    UPDATE sysdiagrams SET [definition] .Write ( 0x160002000300000006000000FFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10305
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000000000000000000000000000000014000000A812000000000000, null, 0) WHERE diagram_id = @newid -- index:10337
    UPDATE sysdiagrams SET [definition] .Write ( 0x53006300680065006D0061002000550044005600200044006500660061007500, null, 0) WHERE diagram_id = @newid -- index:10369
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C00740000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10401
    UPDATE sysdiagrams SET [definition] .Write ( 0x26000200FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10433
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000000000000000000000000000001F0000001600000000000000, null, 0) WHERE diagram_id = @newid -- index:10465
    UPDATE sysdiagrams SET [definition] .Write ( 0x440053005200450046002D0053004300480045004D0041002D0043004F004E00, null, 0) WHERE diagram_id = @newid -- index:10497
    UPDATE sysdiagrams SET [definition] .Write ( 0x540045004E005400530000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10529
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C0002010500000007000000FFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10561
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000200000006203000000000000, null, 0) WHERE diagram_id = @newid -- index:10593
    UPDATE sysdiagrams SET [definition] .Write ( 0x53006300680065006D0061002000550044005600200044006500660061007500, null, 0) WHERE diagram_id = @newid -- index:10625
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C007400200050006F0073007400200056003600000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10657
    UPDATE sysdiagrams SET [definition] .Write ( 0x36000200FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10689
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000000000000000000000000000002E0000001200000000000000, null, 0) WHERE diagram_id = @newid -- index:10721
    UPDATE sysdiagrams SET [definition] .Write ( 0x0C00000000000000000000000100260000007300630068005F006C0061006200, null, 0) WHERE diagram_id = @newid -- index:10753
    UPDATE sysdiagrams SET [definition] .Write ( 0x65006C0073005F00760069007300690062006C0065000000010000000B000000, null, 0) WHERE diagram_id = @newid -- index:10785
    UPDATE sysdiagrams SET [definition] .Write ( 0x1E00000000000000000000000000000000000000640000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10817
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000010000000100000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10849
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000D002000006002800000041006300740069007600650054006100, null, 0) WHERE diagram_id = @newid -- index:10881
    UPDATE sysdiagrams SET [definition] .Write ( 0x62006C00650056006900650077004D006F006400650000000100000008000400, null, 0) WHERE diagram_id = @newid -- index:10913
    UPDATE sysdiagrams SET [definition] .Write ( 0x000031000000200000005400610062006C00650056006900650077004D006F00, null, 0) WHERE diagram_id = @newid -- index:10945
    UPDATE sysdiagrams SET [definition] .Write ( 0x640065003A00300000000100000008003A00000034002C0030002C0032003800, null, 0) WHERE diagram_id = @newid -- index:10977
    UPDATE sysdiagrams SET [definition] .Write ( 0x34002C0030002C0031003900380030002C0031002C0031003600320030002C00, null, 0) WHERE diagram_id = @newid -- index:11009
    UPDATE sysdiagrams SET [definition] .Write ( 0x35002C0031003000380030000000200000005400610062006C00650056006900, null, 0) WHERE diagram_id = @newid -- index:11041
    UPDATE sysdiagrams SET [definition] .Write ( 0x650077004D006F00640065003A00310000000100000008001E00000032002C00, null, 0) WHERE diagram_id = @newid -- index:11073
    UPDATE sysdiagrams SET [definition] .Write ( 0x30002C003200380034002C0030002C0032003400370035000000200000005400, null, 0) WHERE diagram_id = @newid -- index:11105
    UPDATE sysdiagrams SET [definition] .Write ( 0x610062006C00650056006900650077004D006F00640065003A00320000000100, null, 0) WHERE diagram_id = @newid -- index:11137
    UPDATE sysdiagrams SET [definition] .Write ( 0x000008001E00000032002C0030002C003200380034002C0030002C0031003900, null, 0) WHERE diagram_id = @newid -- index:11169
    UPDATE sysdiagrams SET [definition] .Write ( 0x380030000000200000005400610062006C00650056006900650077004D006F00, null, 0) WHERE diagram_id = @newid -- index:11201
    UPDATE sysdiagrams SET [definition] .Write ( 0x640065003A00330000000100000008001E00000032002C0030002C0032003800, null, 0) WHERE diagram_id = @newid -- index:11233
    UPDATE sysdiagrams SET [definition] .Write ( 0x34002C0030002C0031003900380030000000200000005400610062006C006500, null, 0) WHERE diagram_id = @newid -- index:11265
    UPDATE sysdiagrams SET [definition] .Write ( 0x56006900650077004D006F00640065003A00340000000100000008003E000000, null, 0) WHERE diagram_id = @newid -- index:11297
    UPDATE sysdiagrams SET [definition] .Write ( 0x34002C0030002C003200380034002C0030002C0031003900380030002C003100, null, 0) WHERE diagram_id = @newid -- index:11329
    UPDATE sysdiagrams SET [definition] .Write ( 0x32002C0032003300340030002C00310031002C00310034003400300000000200, null, 0) WHERE diagram_id = @newid -- index:11361
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000200000000000000000000000000000000000000D0020000060028000000, null, 0) WHERE diagram_id = @newid -- index:11393
    UPDATE sysdiagrams SET [definition] .Write ( 0x4100630074006900760065005400610062006C00650056006900650077004D00, null, 0) WHERE diagram_id = @newid -- index:11425
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F00640065000000010000000800040000003100000020000000540061006200, null, 0) WHERE diagram_id = @newid -- index:11457
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C00650056006900650077004D006F00640065003A0030000000010000000800, null, 0) WHERE diagram_id = @newid -- index:11489
    UPDATE sysdiagrams SET [definition] .Write ( 0x3A00000034002C0030002C003200380034002C0030002C003100390038003000, null, 0) WHERE diagram_id = @newid -- index:11521
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C0031002C0031003600320030002C0035002C00310030003800300000002000, null, 0) WHERE diagram_id = @newid -- index:11553
    UPDATE sysdiagrams SET [definition] .Write ( 0x00005400610062006C00650056006900650077004D006F00640065003A003100, null, 0) WHERE diagram_id = @newid -- index:11585
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000100000008001E00000032002C0030002C003200380034002C0030002C00, null, 0) WHERE diagram_id = @newid -- index:11617
    UPDATE sysdiagrams SET [definition] .Write ( 0x32003400370035000000200000005400610062006C0065005600690065007700, null, 0) WHERE diagram_id = @newid -- index:11649
    UPDATE sysdiagrams SET [definition] .Write ( 0x4D006F00640065003A00320000000100000008001E00000032002C0030002C00, null, 0) WHERE diagram_id = @newid -- index:11681
    UPDATE sysdiagrams SET [definition] .Write ( 0x3200380034002C0030002C003100390038003000000020000000540061006200, null, 0) WHERE diagram_id = @newid -- index:11713
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C00650056006900650077004D006F00640065003A0033000000010000000800, null, 0) WHERE diagram_id = @newid -- index:11745
    UPDATE sysdiagrams SET [definition] .Write ( 0x1E00000032002C0030002C003200380034002C0030002C003100390038003000, null, 0) WHERE diagram_id = @newid -- index:11777
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000200000005400610062006C00650056006900650077004D006F0064006500, null, 0) WHERE diagram_id = @newid -- index:11809
    UPDATE sysdiagrams SET [definition] .Write ( 0x3A00340000000100000008003E00000034002C0030002C003200380034002C00, null, 0) WHERE diagram_id = @newid -- index:11841
    UPDATE sysdiagrams SET [definition] .Write ( 0x30002C0031003900380030002C00310032002C0032003300340030002C003100, null, 0) WHERE diagram_id = @newid -- index:11873
    UPDATE sysdiagrams SET [definition] .Write ( 0x31002C0031003400340030000000030000000300000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:11905
    UPDATE sysdiagrams SET [definition] .Write ( 0x000000000000D002000006002800000041006300740069007600650054006100, null, 0) WHERE diagram_id = @newid -- index:11937
    UPDATE sysdiagrams SET [definition] .Write ( 0x62006C00650056006900650077004D006F006400650000000100000008000400, null, 0) WHERE diagram_id = @newid -- index:11969
    UPDATE sysdiagrams SET [definition] .Write ( 0x000031000000200000005400610062006C00650056006900650077004D006F00, null, 0) WHERE diagram_id = @newid -- index:12001
    UPDATE sysdiagrams SET [definition] .Write ( 0x640065003A00300000000100000008003A00000034002C0030002C0032003800, null, 0) WHERE diagram_id = @newid -- index:12033
    UPDATE sysdiagrams SET [definition] .Write ( 0x34002C0030002C0031003900380030002C0031002C0031003600320030002C00, null, 0) WHERE diagram_id = @newid -- index:12065
    UPDATE sysdiagrams SET [definition] .Write ( 0x35002C0031003000380030000000200000005400610062006C00650056006900, null, 0) WHERE diagram_id = @newid -- index:12097
    UPDATE sysdiagrams SET [definition] .Write ( 0x650077004D006F00640065003A00310000000100000008001E00000032002C00, null, 0) WHERE diagram_id = @newid -- index:12129
    UPDATE sysdiagrams SET [definition] .Write ( 0x30002C003200380034002C0030002C0032003400370035000000200000005400, null, 0) WHERE diagram_id = @newid -- index:12161
    UPDATE sysdiagrams SET [definition] .Write ( 0x610062006C00650056006900650077004D006F00640065003A00320000000100, null, 0) WHERE diagram_id = @newid -- index:12193
    UPDATE sysdiagrams SET [definition] .Write ( 0x000008001E00000032002C0030002C003200380034002C0030002C0031003900, null, 0) WHERE diagram_id = @newid -- index:12225
    UPDATE sysdiagrams SET [definition] .Write ( 0x380030000000200000005400610062006C00650056006900650077004D006F00, null, 0) WHERE diagram_id = @newid -- index:12257
    UPDATE sysdiagrams SET [definition] .Write ( 0x640065003A00330000000100000008001E00000032002C0030002C0032003800, null, 0) WHERE diagram_id = @newid -- index:12289
    UPDATE sysdiagrams SET [definition] .Write ( 0x34002C0030002C0031003900380030000000200000005400610062006C006500, null, 0) WHERE diagram_id = @newid -- index:12321
    UPDATE sysdiagrams SET [definition] .Write ( 0x56006900650077004D006F00640065003A00340000000100000008003E000000, null, 0) WHERE diagram_id = @newid -- index:12353
    UPDATE sysdiagrams SET [definition] .Write ( 0x34002C0030002C003200380034002C0030002C0031003900380030002C003100, null, 0) WHERE diagram_id = @newid -- index:12385
    UPDATE sysdiagrams SET [definition] .Write ( 0x32002C0032003300340030002C00310031002C00310034003400300000000400, null, 0) WHERE diagram_id = @newid -- index:12417
    UPDATE sysdiagrams SET [definition] .Write ( 0x000004000000000000003A0000000103D0150100000069004300430047000000, null, 0) WHERE diagram_id = @newid -- index:12449
    UPDATE sysdiagrams SET [definition] .Write ( 0x46004B005F00430061007300650043006F006E0074006100630074005F004300, null, 0) WHERE diagram_id = @newid -- index:12481
    UPDATE sysdiagrams SET [definition] .Write ( 0x61007300650000000000000000000000C4020000000005000000050000000400, null, 0) WHERE diagram_id = @newid -- index:12513
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000080000000100000098DF9B0E0000000000000000AD070000000000060000, null, 0) WHERE diagram_id = @newid -- index:12545
    UPDATE sysdiagrams SET [definition] .Write ( 0x000600000000000000400000000103D015010000006900430043004700000046, null, 0) WHERE diagram_id = @newid -- index:12577
    UPDATE sysdiagrams SET [definition] .Write ( 0x004B005F00430061007300650043006F006E0074006100630074005F0043006F, null, 0) WHERE diagram_id = @newid -- index:12609
    UPDATE sysdiagrams SET [definition] .Write ( 0x006E00740061006300740000000000000000000000C402000000000700000007, null, 0) WHERE diagram_id = @newid -- index:12641
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000006000000080000000100000058DE9B0E0000000000000000AD07000000, null, 0) WHERE diagram_id = @newid -- index:12673
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000080000000800000000000000000000000000000000000000D00200000600, null, 0) WHERE diagram_id = @newid -- index:12705
    UPDATE sysdiagrams SET [definition] .Write ( 0x280000004100630074006900760065005400610062006C006500560069006500, null, 0) WHERE diagram_id = @newid -- index:12737
    UPDATE sysdiagrams SET [definition] .Write ( 0x77004D006F006400650000000100000008000400000031000000200000005400, null, 0) WHERE diagram_id = @newid -- index:12769
    UPDATE sysdiagrams SET [definition] .Write ( 0x610062006C00650056006900650077004D006F00640065003A00300000000100, null, 0) WHERE diagram_id = @newid -- index:12801
    UPDATE sysdiagrams SET [definition] .Write ( 0x000008003A00000034002C0030002C003200380034002C0030002C0031003900, null, 0) WHERE diagram_id = @newid -- index:12833
    UPDATE sysdiagrams SET [definition] .Write ( 0x380030002C0031002C0031003600320030002C0035002C003100300038003000, null, 0) WHERE diagram_id = @newid -- index:12865
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000200000005400610062006C00650056006900650077004D006F0064006500, null, 0) WHERE diagram_id = @newid -- index:12897
    UPDATE sysdiagrams SET [definition] .Write ( 0x3A00310000000100000008001E00000032002C0030002C003200380034002C00, null, 0) WHERE diagram_id = @newid -- index:12929
    UPDATE sysdiagrams SET [definition] .Write ( 0x30002C0032003400370035000000200000005400610062006C00650056006900, null, 0) WHERE diagram_id = @newid -- index:12961
    UPDATE sysdiagrams SET [definition] .Write ( 0x650077004D006F00640065003A00320000000100000008001E00000032002C00, null, 0) WHERE diagram_id = @newid -- index:12993
    UPDATE sysdiagrams SET [definition] .Write ( 0x30002C003200380034002C0030002C0031003900380030000000200000005400, null, 0) WHERE diagram_id = @newid -- index:13025
    UPDATE sysdiagrams SET [definition] .Write ( 0x610062006C00650056006900650077004D006F00640065003A00330000000100, null, 0) WHERE diagram_id = @newid -- index:13057
    UPDATE sysdiagrams SET [definition] .Write ( 0x000008001E00000032002C0030002C003200380034002C0030002C0031003900, null, 0) WHERE diagram_id = @newid -- index:13089
    UPDATE sysdiagrams SET [definition] .Write ( 0x380030000000200000005400610062006C00650056006900650077004D006F00, null, 0) WHERE diagram_id = @newid -- index:13121
    UPDATE sysdiagrams SET [definition] .Write ( 0x640065003A00340000000100000008003E00000034002C0030002C0032003800, null, 0) WHERE diagram_id = @newid -- index:13153
    UPDATE sysdiagrams SET [definition] .Write ( 0x34002C0030002C0031003900380030002C00310032002C003200330034003000, null, 0) WHERE diagram_id = @newid -- index:13185
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C00310031002C00310034003400300000000900000009000000000000005200, null, 0) WHERE diagram_id = @newid -- index:13217
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000010100000100000050006C006100740066006F0072006D00000046004B00, null, 0) WHERE diagram_id = @newid -- index:13249
    UPDATE sysdiagrams SET [definition] .Write ( 0x5F0043006F006E0074006100630074005F00520065006600500072006F007600, null, 0) WHERE diagram_id = @newid -- index:13281
    UPDATE sysdiagrams SET [definition] .Write ( 0x69006400650072005400690074006C00650000000000000000000000C4020000, null, 0) WHERE diagram_id = @newid -- index:13313
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000A0000000A00000009000000080000000100000098DE9B0E000000000000, null, 0) WHERE diagram_id = @newid -- index:13345
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000AD0700000000000B0000000B000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:13377
    UPDATE sysdiagrams SET [definition] .Write ( 0x00D00200000600280000004100630074006900760065005400610062006C0065, null, 0) WHERE diagram_id = @newid -- index:13409
    UPDATE sysdiagrams SET [definition] .Write ( 0x0056006900650077004D006F0064006500000001000000080004000000310000, null, 0) WHERE diagram_id = @newid -- index:13441
    UPDATE sysdiagrams SET [definition] .Write ( 0x00200000005400610062006C00650056006900650077004D006F00640065003A, null, 0) WHERE diagram_id = @newid -- index:13473
    UPDATE sysdiagrams SET [definition] .Write ( 0x00300000000100000008003A00000034002C0030002C003200380034002C0030, null, 0) WHERE diagram_id = @newid -- index:13505
    UPDATE sysdiagrams SET [definition] .Write ( 0x002C0031003900380030002C0031002C0031003600320030002C0035002C0031, null, 0) WHERE diagram_id = @newid -- index:13537
    UPDATE sysdiagrams SET [definition] .Write ( 0x003000380030000000200000005400610062006C00650056006900650077004D, null, 0) WHERE diagram_id = @newid -- index:13569
    UPDATE sysdiagrams SET [definition] .Write ( 0x006F00640065003A00310000000100000008001E00000032002C0030002C0032, null, 0) WHERE diagram_id = @newid -- index:13601
    UPDATE sysdiagrams SET [definition] .Write ( 0x00380034002C0030002C0032003900350035000000200000005400610062006C, null, 0) WHERE diagram_id = @newid -- index:13633
    UPDATE sysdiagrams SET [definition] .Write ( 0x00650056006900650077004D006F00640065003A00320000000100000008001E, null, 0) WHERE diagram_id = @newid -- index:13665
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000032002C0030002C003200380034002C0030002C00310039003800300000, null, 0) WHERE diagram_id = @newid -- index:13697
    UPDATE sysdiagrams SET [definition] .Write ( 0x00200000005400610062006C00650056006900650077004D006F00640065003A, null, 0) WHERE diagram_id = @newid -- index:13729
    UPDATE sysdiagrams SET [definition] .Write ( 0x00330000000100000008001E00000032002C0030002C003200380034002C0030, null, 0) WHERE diagram_id = @newid -- index:13761
    UPDATE sysdiagrams SET [definition] .Write ( 0x002C0031003900380030000000200000005400610062006C0065005600690065, null, 0) WHERE diagram_id = @newid -- index:13793
    UPDATE sysdiagrams SET [definition] .Write ( 0x0077004D006F00640065003A00340000000100000008003E00000034002C0030, null, 0) WHERE diagram_id = @newid -- index:13825
    UPDATE sysdiagrams SET [definition] .Write ( 0x002C003200380034002C0030002C0031003900380030002C00310032002C0032, null, 0) WHERE diagram_id = @newid -- index:13857
    UPDATE sysdiagrams SET [definition] .Write ( 0x003300340030002C00310031002C00310034003400300000000D0000000D0000, null, 0) WHERE diagram_id = @newid -- index:13889
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000004E00000001FFD0150100000050006C006100740066006F0072006D, null, 0) WHERE diagram_id = @newid -- index:13921
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000046004B005F0043006F006E0074006100630074005F0052006500660043, null, 0) WHERE diagram_id = @newid -- index:13953
    UPDATE sysdiagrams SET [definition] .Write ( 0x006F006E007400610063007400540079007000650000000000000000000000C4, null, 0) WHERE diagram_id = @newid -- index:13985
    UPDATE sysdiagrams SET [definition] .Write ( 0x02000000000E0000000E0000000D000000080000000100000018E29B0E000000, null, 0) WHERE diagram_id = @newid -- index:14017
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000AD0F00000100000F0000000F000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:14049
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000D0020000060028000000410063007400690076006500540061006200, null, 0) WHERE diagram_id = @newid -- index:14081
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C00650056006900650077004D006F0064006500000001000000080004000000, null, 0) WHERE diagram_id = @newid -- index:14113
    UPDATE sysdiagrams SET [definition] .Write ( 0x31000000200000005400610062006C00650056006900650077004D006F006400, null, 0) WHERE diagram_id = @newid -- index:14145
    UPDATE sysdiagrams SET [definition] .Write ( 0x65003A00300000000100000008003A00000034002C0030002C00320038003400, null, 0) WHERE diagram_id = @newid -- index:14177
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C0030002C0031003900380030002C0031002C0031003600320030002C003500, null, 0) WHERE diagram_id = @newid -- index:14209
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C0031003000380030000000200000005400610062006C006500560069006500, null, 0) WHERE diagram_id = @newid -- index:14241
    UPDATE sysdiagrams SET [definition] .Write ( 0x77004D006F00640065003A00310000000100000008001E00000032002C003000, null, 0) WHERE diagram_id = @newid -- index:14273
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C003200380034002C0030002C00320034003700350000002000000054006100, null, 0) WHERE diagram_id = @newid -- index:14305
    UPDATE sysdiagrams SET [definition] .Write ( 0x62006C00650056006900650077004D006F00640065003A003200000001000000, null, 0) WHERE diagram_id = @newid -- index:14337
    UPDATE sysdiagrams SET [definition] .Write ( 0x08001E00000032002C0030002C003200380034002C0030002C00310039003800, null, 0) WHERE diagram_id = @newid -- index:14369
    UPDATE sysdiagrams SET [definition] .Write ( 0x30000000200000005400610062006C00650056006900650077004D006F006400, null, 0) WHERE diagram_id = @newid -- index:14401
    UPDATE sysdiagrams SET [definition] .Write ( 0x65003A00330000000100000008001E00000032002C0030002C00320038003400, null, 0) WHERE diagram_id = @newid -- index:14433
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C0030002C0031003900380030000000200000005400610062006C0065005600, null, 0) WHERE diagram_id = @newid -- index:14465
    UPDATE sysdiagrams SET [definition] .Write ( 0x6900650077004D006F00640065003A00340000000100000008003E0000003400, null, 0) WHERE diagram_id = @newid -- index:14497
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C0030002C003200380034002C0030002C0031003900380030002C0031003200, null, 0) WHERE diagram_id = @newid -- index:14529
    UPDATE sysdiagrams SET [definition] .Write ( 0x2C0032003300340030002C00310031002C003100340034003000000010000000, null, 0) WHERE diagram_id = @newid -- index:14561
    UPDATE sysdiagrams SET [definition] .Write ( 0x100000000000000054000000010100000100000050006C006100740066006F00, null, 0) WHERE diagram_id = @newid -- index:14593
    UPDATE sysdiagrams SET [definition] .Write ( 0x72006D00000046004B005F0043006F006E0074006100630074005F0052006500, null, 0) WHERE diagram_id = @newid -- index:14625
    UPDATE sysdiagrams SET [definition] .Write ( 0x6600530061006C00750074006100740069006F006E0054007900700065000000, null, 0) WHERE diagram_id = @newid -- index:14657
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000C40200000000110000001100000010000000080000000100, null, 0) WHERE diagram_id = @newid -- index:14689
    UPDATE sysdiagrams SET [definition] .Write ( 0x000018E09B0E0000000000000000AD0F00000100001200000012000000000000, null, 0) WHERE diagram_id = @newid -- index:14721
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000000000000000000000000D0020000060028000000410063007400690076, null, 0) WHERE diagram_id = @newid -- index:14753
    UPDATE sysdiagrams SET [definition] .Write ( 0x0065005400610062006C00650056006900650077004D006F0064006500000001, null, 0) WHERE diagram_id = @newid -- index:14785
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000008000400000031000000200000005400610062006C0065005600690065, null, 0) WHERE diagram_id = @newid -- index:14817
    UPDATE sysdiagrams SET [definition] .Write ( 0x0077004D006F00640065003A00300000000100000008003A00000034002C0030, null, 0) WHERE diagram_id = @newid -- index:14849
    UPDATE sysdiagrams SET [definition] .Write ( 0x002C003200380034002C0030002C0031003900380030002C0031002C00310036, null, 0) WHERE diagram_id = @newid -- index:14881
    UPDATE sysdiagrams SET [definition] .Write ( 0x00320030002C0035002C0031003000380030000000200000005400610062006C, null, 0) WHERE diagram_id = @newid -- index:14913
    UPDATE sysdiagrams SET [definition] .Write ( 0x00650056006900650077004D006F00640065003A00310000000100000008001E, null, 0) WHERE diagram_id = @newid -- index:14945
    UPDATE sysdiagrams SET [definition] .Write ( 0x00000032002C0030002C003200380034002C0030002C00320034003700350000, null, 0) WHERE diagram_id = @newid -- index:14977
    UPDATE sysdiagrams SET [definition] .Write ( 0x00200000005400610062006C00650056006900650077004D006F00640065003A, null, 0) WHERE diagram_id = @newid -- index:15009
    UPDATE sysdiagrams SET [definition] .Write ( 0x00320000000100000008001E00000032002C0030002C003200380034002C0030, null, 0) WHERE diagram_id = @newid -- index:15041
    UPDATE sysdiagrams SET [definition] .Write ( 0x002C0031003900380030000000200000005400610062006C0065005600690065, null, 0) WHERE diagram_id = @newid -- index:15073
    UPDATE sysdiagrams SET [definition] .Write ( 0x0077004D006F00640065003A00330000000100000008001E00000032002C0030, null, 0) WHERE diagram_id = @newid -- index:15105
    UPDATE sysdiagrams SET [definition] .Write ( 0x002C003200380034002C0030002C003100390038003000000020000000540061, null, 0) WHERE diagram_id = @newid -- index:15137
    UPDATE sysdiagrams SET [definition] .Write ( 0x0062006C00650056006900650077004D006F00640065003A0034000000010000, null, 0) WHERE diagram_id = @newid -- index:15169
    UPDATE sysdiagrams SET [definition] .Write ( 0x0008003E00000034002C0030002C003200380034002C0030002C003100390038, null, 0) WHERE diagram_id = @newid -- index:15201
    UPDATE sysdiagrams SET [definition] .Write ( 0x0030002C00310032002C0032003300340030002C00310031002C003100340034, null, 0) WHERE diagram_id = @newid -- index:15233
    UPDATE sysdiagrams SET [definition] .Write ( 0x003000000013000000130000000000000042000000010007770100000050006C, null, 0) WHERE diagram_id = @newid -- index:15265
    UPDATE sysdiagrams SET [definition] .Write ( 0x006100740066006F0072006D00000046004B005F0043006F006E007400610063, null, 0) WHERE diagram_id = @newid -- index:15297
    UPDATE sysdiagrams SET [definition] .Write ( 0x0074005F005200650066005300740061007400650000000000000000000000C4, null, 0) WHERE diagram_id = @newid -- index:15329
    UPDATE sysdiagrams SET [definition] .Write ( 0x0200000000140000001400000013000000080000000100000058E19B0E000000, null, 0) WHERE diagram_id = @newid -- index:15361
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000AD0F00000100001E00000006000000020000000100000070000000, null, 0) WHERE diagram_id = @newid -- index:15393
    UPDATE sysdiagrams SET [definition] .Write ( 0x8B0000000400000003000000010000003C000000010000000900000008000000, null, 0) WHERE diagram_id = @newid -- index:15425
    UPDATE sysdiagrams SET [definition] .Write ( 0x0200000046000000A90000000D0000000B000000020000005C00000047000000, null, 0) WHERE diagram_id = @newid -- index:15457
    UPDATE sysdiagrams SET [definition] .Write ( 0x100000000F0000000200000047000000CC000000130000001200000002000000, null, 0) WHERE diagram_id = @newid -- index:15489
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000023000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:15521
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:15553
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:15585
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:15617
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:15649
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:15681
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:15713
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:15745
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:15777
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:15809
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:15841
    UPDATE sysdiagrams SET [definition] .Write ( 0xDBE6B0E91C81D011AD5100A0C90F573900000200601F8CACF560CC0102020000, null, 0) WHERE diagram_id = @newid -- index:15873
    UPDATE sysdiagrams SET [definition] .Write ( 0x10484500000000000000000000000000000000005A0100004400610074006100, null, 0) WHERE diagram_id = @newid -- index:15905
    UPDATE sysdiagrams SET [definition] .Write ( 0x200053006F0075007200630065003D002E003B0049006E006900740069006100, null, 0) WHERE diagram_id = @newid -- index:15937
    UPDATE sysdiagrams SET [definition] .Write ( 0x6C00200043006100740061006C006F0067003D00430061007200650057006500, null, 0) WHERE diagram_id = @newid -- index:15969
    UPDATE sysdiagrams SET [definition] .Write ( 0x620051004900440062003B0049006E0074006500670072006100740065006400, null, 0) WHERE diagram_id = @newid -- index:16001
    UPDATE sysdiagrams SET [definition] .Write ( 0x2000530065006300750072006900740079003D0054007200750065003B004D00, null, 0) WHERE diagram_id = @newid -- index:16033
    UPDATE sysdiagrams SET [definition] .Write ( 0x75006C007400690070006C006500410063007400690076006500520065007300, null, 0) WHERE diagram_id = @newid -- index:16065
    UPDATE sysdiagrams SET [definition] .Write ( 0x75006C00740053006500740073003D00460061006C00730065003B0050006100, null, 0) WHERE diagram_id = @newid -- index:16097
    UPDATE sysdiagrams SET [definition] .Write ( 0x63006B00650074002000530069007A0065003D0034003000390036003B004100, null, 0) WHERE diagram_id = @newid -- index:16129
    UPDATE sysdiagrams SET [definition] .Write ( 0x700070006C00690063006100740069006F006E0020004E0061006D0065003D00, null, 0) WHERE diagram_id = @newid -- index:16161
    UPDATE sysdiagrams SET [definition] .Write ( 0x22004D006900630072006F0073006F00660074002000530051004C0020005300, null, 0) WHERE diagram_id = @newid -- index:16193
    UPDATE sysdiagrams SET [definition] .Write ( 0x6500720076006500720020004D0061006E006100670065006D0065006E007400, null, 0) WHERE diagram_id = @newid -- index:16225
    UPDATE sysdiagrams SET [definition] .Write ( 0x2000530074007500640069006F00220000000080050014000000440069006100, null, 0) WHERE diagram_id = @newid -- index:16257
    UPDATE sysdiagrams SET [definition] .Write ( 0x6700720061006D005F0030000000000226001E00000052006500660043006F00, null, 0) WHERE diagram_id = @newid -- index:16289
    UPDATE sysdiagrams SET [definition] .Write ( 0x6E007400610063007400540079007000650000001200000050006C0061007400, null, 0) WHERE diagram_id = @newid -- index:16321
    UPDATE sysdiagrams SET [definition] .Write ( 0x66006F0072006D0000000002260022000000520065006600500072006F007600, null, 0) WHERE diagram_id = @newid -- index:16353
    UPDATE sysdiagrams SET [definition] .Write ( 0x69006400650072005400690074006C006500000008000000640062006F000000, null, 0) WHERE diagram_id = @newid -- index:16385
    UPDATE sysdiagrams SET [definition] .Write ( 0x000226000A000000430061007300650000000A00000069004300430047000000, null, 0) WHERE diagram_id = @newid -- index:16417
    UPDATE sysdiagrams SET [definition] .Write ( 0x000226001000000043006F006E00740061006300740000001200000050006C00, null, 0) WHERE diagram_id = @newid -- index:16449
    UPDATE sysdiagrams SET [definition] .Write ( 0x6100740066006F0072006D000000000226001800000043006100730065004300, null, 0) WHERE diagram_id = @newid -- index:16481
    UPDATE sysdiagrams SET [definition] .Write ( 0x6F006E00740061006300740000000A0000006900430043004700000000022600, null, 0) WHERE diagram_id = @newid -- index:16513
    UPDATE sysdiagrams SET [definition] .Write ( 0x24000000520065006600530061006C00750074006100740069006F006E005400, null, 0) WHERE diagram_id = @newid -- index:16545
    UPDATE sysdiagrams SET [definition] .Write ( 0x790070006500000008000000640062006F000000000224001200000052006500, null, 0) WHERE diagram_id = @newid -- index:16577
    UPDATE sysdiagrams SET [definition] .Write ( 0x660053007400610074006500000008000000640062006F00000001000000D685, null, 0) WHERE diagram_id = @newid -- index:16609
    UPDATE sysdiagrams SET [definition] .Write ( 0x09B3BB6BF2459AB8371664F0327008004E0000007B0039003100350031003000, null, 0) WHERE diagram_id = @newid -- index:16641
    UPDATE sysdiagrams SET [definition] .Write ( 0x3600300038002D0038003800300039002D0034003000320030002D0038003800, null, 0) WHERE diagram_id = @newid -- index:16673
    UPDATE sysdiagrams SET [definition] .Write ( 0x390037002D004600420041003000350037004500320032004400350034007D00, null, 0) WHERE diagram_id = @newid -- index:16705
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:16737
    UPDATE sysdiagrams SET [definition] .Write ( 0x010003000000000000000C0000000B0000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:16769
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:16801
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:16833
    UPDATE sysdiagrams SET [definition] .Write ( 0x0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:16865
    UPDATE sysdiagrams SET [definition] .Write ( 0x62885214, null, 0) WHERE diagram_id = @newid -- index:16897
 
    PRINT '=== Finished writing diagram id ' + CAST(@newid AS VARCHAR(100)) + '  ==='
    PRINT '=== Refresh your Databases-[DbName]-Database Diagrams to see the new diagram ==='
END TRY
BEGIN CATCH
    -- If we got here, the [definition] updates didn't complete, so delete the diagram row
    -- (and hope it doesn't fail!)
    DELETE FROM sysdiagrams WHERE diagram_id = @newid
    PRINT 'XxXxX ' + Error_Message() + ' XxXxX'
    PRINT 'XxXxX END Tool_ScriptDiagram2005 - fix the error before running again XxXxX'
    RETURN
END CATCH
