SELECT
	--[AreaForwardingID]
	--,[AreaGUID]
	[AreaPath]
	,[AreaName]
	--,[AreaProjectGUID]
	--,[CG_Business_ActualEstimate]
	--,[CG_Business_BusinessReason]
	--,[CG_Business_CrossProductImplications]
	--,[CG_Business_CrossTeamImplications]
	--,[CG_Business_InitialComplexityEstimate]
	--,[CG_Business_MarketProblem]
	--,[CG_CustomerIssue_ImpactedCustomers]
	--,[CG_DBType]
	--,[CG_InstallType]
	--,[CG_ProductVersions]
	--,[CG_Projects]
	--,[CG_SupportedProduct]
	--,[CG_SupportedVersion]
	--,[CG_Tags]
	,[CurrentWorkItemBK]
	,[CWQI_BugResolution]
	--,[CWQI_DeliveryType]
	--,[CWQI_MMF]
	--,[IterationForwardingID]
	--,[IterationGUID]
	,[IterationName]
	,[IterationPath]
	--,[IterationProjectGUID]
	,convert(VARCHAR, [LastUpdatedDateTime], 101) AS LastUpdatedDateTime
	,[Microsoft_VSTS_Build_FoundIn]
	,[Microsoft_VSTS_Build_IntegrationBuild]
	--,[Microsoft_VSTS_CMMI_Blocked]
	--,[Microsoft_VSTS_Common_ActivatedBy]
	--,[Microsoft_VSTS_Common_ActivatedDate]
	--,[Microsoft_VSTS_Common_Activity]
	--,[Microsoft_VSTS_Common_BusinessValue]
	--,[Microsoft_VSTS_Common_ClosedBy]
	--,[Microsoft_VSTS_Common_ClosedDate]
	,[Microsoft_VSTS_Common_Issue]
	,[Microsoft_VSTS_Common_Priority]
	,[Microsoft_VSTS_Common_ResolvedBy]
	,convert(VARCHAR, [Microsoft_VSTS_Common_ResolvedDate], 101) AS ResolvedDate
	,[Microsoft_VSTS_Common_ResolvedReason]
	,[Microsoft_VSTS_Common_Risk]
	,[Microsoft_VSTS_Common_Severity]
	,[Microsoft_VSTS_Common_StackRank]
	,[Microsoft_VSTS_Common_Triage]
	,[Microsoft_VSTS_Scheduling_CompletedWork]
	,convert(VARCHAR, [Microsoft_VSTS_Scheduling_DueDate], 101) AS DueDate
	,[Microsoft_VSTS_Scheduling_Effort]
	,convert(VARCHAR, [Microsoft_VSTS_Scheduling_FinishDate], 101) AS FinishDate
	,[Microsoft_VSTS_Scheduling_OriginalEstimate]
	,[Microsoft_VSTS_Scheduling_RemainingWork]
	,convert(VARCHAR, [Microsoft_VSTS_Scheduling_StartDate], 101) AS StartDate
	,[Microsoft_VSTS_Scheduling_StoryPoints]
	,[Microsoft_VSTS_TCM_AutomationStatus]
	--,[ParentAreaGUID]
	--,[ParentIterationGUID]
	--,[PBI_Theme]
	,[PreviousState]
	,[ProjectIsDeleted]
	--,[ProjectNodeGUID]
	--,[ProjectNodeName]
	--,[ProjectNodeSK]
	--,[ProjectNodeType]
	--,[ProjectNodeTypeName]
	--,[ProjectPath]
	,[System_AssignedTo]
	,[System_ChangedBy]
	,convert(VARCHAR, [System_ChangedDate], 101) AS ChangedDate
	,[System_CreatedBy]
	,convert(VARCHAR, [System_CreatedDate], 101) AS CreatedDate
	,[System_Id]
	,[System_Reason]
	,[System_Rev]
	,convert(VARCHAR, [System_RevisedDate], 101) AS RevisedDate
	,[System_State]
	,[System_Title]
	,[System_WorkItemType]
	,[TeamProjectCollectionSK]
	,[WorkItem]
	,[WorkItemSK]
FROM [tfs_warehouse].[dbo].[CurrentWorkItemView]
WHERE [ProjectNodeGUID] = '41423425-7C8F-4503-A8F4-5F3A1CEFB415' -- mcg
	AND [System_WorkItemType] = 'Bug'
	AND [System_CreatedDate] > '2013-01-01'
	AND [System_CreatedDate] < '2013-02-8'
ORDER BY AreaPath
	,IterationName
