SELECT [FldID]
	, [FldIDstr]
	, [ParentFldID]
	, [NewParentFldID]
	, [ParentFldIDstr]
	, [Name]
	, [NewName]
	, [fDeleted]
	, [ReferenceName]
	, [IntheboxName]
	, [ColName]
FROM [Tfs_MillimanSandbox].[dbo].[Fields]
ORDER BY [Name]
